[project]
name = "karambit-contracts"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.kbt-ststx]
path = "contracts/kbt-ststx.clar"
clarity_version = 2
epoch = 2.5

[contracts.kbt-sy]
path = "contracts/kbt-sy.clar"
clarity_version = 2
epoch = 2.5

[contracts.kbt-pt]
path = "contracts/kbt-pt.clar"
clarity_version = 2
epoch = 2.5

[contracts.kbt-yt]
path = "contracts/kbt-yt.clar"
clarity_version = 2
epoch = 2.5

[contracts.kbt-vault]
path = "contracts/kbt-vault.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
